Data Bootcamp

Professor Michael Waugh

Spring 2018

Nan Jiang

Question #1: Review. Does this code run without error? If so, what does it produce? If not, explain why.

In [2]:
x = [1, 2, 3] 
y = 'bootcamp'
z = x+y

TypeError: can only concatenate list (not "str") to list

Answer:

This code does not run without error. This is because x and y are different in data structure. Specifically, x is a list and y is a string. The addition function can only concatenate list  to list, but not string to list. 

Question #2:Review. For the same x and y as the previous question: What function tells us what type they are? What function tells us how many elements they contain?

In [9]:
type(x)

list

In [10]:
type(y)

str

In [11]:
len(x)

3

In [12]:
len(y)

8

Answer:

Function type() tells the type and function len() tells the number of elements, as shown above.

Question #3: What type is each expression? How can you tell?

In [20]:
a = 2
b = '2'
c = 2.0
d = "2.0"
e = 2>1
f = 'Itamar' > 'Chase'
g = [1, 2]
h = (1, 2)
i = {1: 'one', 2: 'two'}

In [21]:
whos

Variable   Type     Data/Info
-----------------------------
a          int      2
b          str      2
c          float    2.0
d          str      2.0
e          bool     True
f          bool     True
g          list     n=2
h          tuple    n=2
i          dict     n=2
x          list     n=3
y          str      bootcamp


Answer:

The type of each variable can be seen in the table above. By assigning each expression to a variable and using the "whos" command, we can easily display the type of each of them.

Specifically, 2 is an integer, '2' is a string, 2.0 is a float, "2.0" is a string, 2>1 is a boolean, 'Itamar' > 'Chase' is a boolean, [1,2] is a list, (1,2) is a tuple and {1: 'one', 2: 'two'} is a dictionary. 

Question #4: What value does each of these comparisons have?

In [22]:
1>=0

True

In [23]:
1 >= 1

True

In [24]:
1>1

False

In [25]:
1==1

True

In [26]:
1 == 1.0

True

In [28]:
'Spencer' == "Spencer"

True

In [29]:
2**3 > 3**2

False

In [30]:
1 >= 0 or 1 <= 2

True

In [31]:
1 >= 0 and 1 <= 2

True

Question #5: Does this code run without error? If so, what does it produce? If not, how would you fix it?

In [33]:
if 2>1
      print('Yes, 2 is still greater than 1')

SyntaxError: invalid syntax (<ipython-input-33-a0e203583bc3>, line 1)

Answer:

This code does not run without error. The if command should be followed by a ":". I would fix the command simply by adding the missing ":".

In [34]:
if 2>1:
    print('yes, 2 is still greater than 1')

yes, 2 is still greater than 1


Question #6: What is the result of running this code? Why?

In [41]:
if True:
    print('on the one hand')
else:
    print('but on the other hand')

on the one hand


Answer:

This code prints out the phrase "on the one hand". 


What happens if we replace True with False in the first line? What happens if we insert the word not after if in the first line?

In [42]:
if False:
    print('on the one hand')
else:
    print('but on the other hand')

but on the other hand


Answer:
    
Replacing True with False prints out the phrase "but on the other hand".

In [45]:
if not True:
    print('on the one hand')
else:
    print('but on the other hand')

but on the other hand


Answer:

Inserting "not" after if, prints out the phrase "but on the other hand". In this case, "if not true" is essentially the same as "if false". 

Quesiton #7: What is the result of running this code?

In [48]:
cond = True
if cond:
    x = "Chase"
else:
    x = "Dave"
print(x)

Chase


Answer:

The code above gives the result of Chase. 

Question #8: Suppose we have two lists, x = [1, 2, 3, 4] and y = [’x’, ’y’, ’z’]. Adapt the code below to determine which has more elements:

In [55]:
x = [1,2,3,4]
y=['x', 'y', 'z']
if len(x) > len(y):
    print('x has more')
else:
    print("y has at least as many")

x has more


Question #9: Explain in words what slicing does.

Answer:

Through the method of slicing, we can access the elements of strings and lists by specifying the item number in square brackets. The first number in the bracket indicates which element to start from, followed by a ":" that essentially indicates until, and the second number indicates where to stop. Noticeably, python starts numbering from zero, and does not include the element whose order is indicated by the second number. The negative numbering also works, which enables us to count backward from the end of the string or list. 

Question #10: How would you extract (“slice”) the first element (the integer 1) from the list x below? The last element? All but the last element?

In [59]:
x = [1, 2, 3, 4, 5]
x[0]

1

In [60]:
x[-1]

5

In [61]:
x[:-1]

[1, 2, 3, 4]

Question #11: Use slicing to extract each word from sentence = 'This is a sentence; please slice it.' Suggestion: Number every character in sentence by hand.

In [62]:
sentence = 'This is a sentence; please slice it.'

In [71]:
sentence[0:4]

'This'

In [68]:
sentence[5:7]

'is'

In [72]:
sentence[8]

'a'

In [73]:
sentence[10:18]

'sentence'

In [74]:
sentence[20:26]

'please'

In [80]:
sentence[-9:-4]

'slice'

In [78]:
sentence[-3:-1]

'it'

Question #12: Consider the list x = [1, 2, "a", 'b', "fast", 'slow', 3, "Raghu", 'Liuren', 10]

a. How would you slice out the first item? The last item?

b. How would you slice out the items from 'b' to 3 inclusive?

In [81]:
x = [1, 2, "a", 'b', "fast", 'slow', 3, "Raghu", 'Liuren', 10]

In [82]:
x[0]

1

In [83]:
x[-1]

10

In [85]:
x[3:-3]

['b', 'fast', 'slow', 3]

Question #13: Using the same list x, write a loop that prints every element on a new line.

In [87]:
for item in x:
    print(item)

1
2
a
b
fast
slow
3
Raghu
Liuren
10


Question #14: Challenging. Using the same list x, write a loop that prints every element of type str.

In [91]:
for item in x:
    if type(item) == str:
        print(item)

a
b
fast
slow
Raghu
Liuren


Question #15: Use Spyder’s help to find out what the range function does. How would you describe range(3,12,2)? Verify by converting to a list with list(range(3,12,2)).

In [98]:
range?

Answer:

The range function returns an object that produces a sequence of integers, starting from the first number (inclusive) and ending at the second number (exclusive) in the bracket. The third number in the bracket indicates the increment between consecutive integers.

Specifically, range(3,12,2) pulls outs integers starting from 3, with an increment of 2 and ends when the next increment makes the next integer to be pulled out be larger than 12. 

In [97]:
list(range(3,12,2)) 

[3, 5, 7, 9, 11]

Question #16: Challenging. Write a loop that sums the integers from zero to thirty that are multiples of three: 3, 6, etc.

In [116]:
total = 0
x = list(range(0,30,3))
for item in x:
    total = total + item 
print(total)

135


Question #17: Define a function pocket_change() that takes four integers as inputs (numbers of pennies, nickels, dimes, and quarters in your pocket) and returns a floating point number (their dollar value). Run your program with the input (1, 2, 3, 4). Bonus (optional): Report the value with a dollar sign.

In [62]:
def pocket_change(coins):
    return (coins[0]*1 + coins[1]*5 + coins[2]*10 + coins[3]*25)/100

In [61]:
print ("$"+str(pocket_change((1,2,3,4))))

$1.41


Question #18: Challenging. Write a function notsix() that takes a list of integers and returns a (shorter) list of only those that do not begin with a 6. Test it on the list [1234, 6783, 6, 4321, 9876]. Hints: You can create a blank list with x = []. You can append item to it with x.append(item).


In [139]:
x = []
def notsix(integers):
    for item in integers:
         if str(item)[0] != "6":
                x.append(item)
    return x


In [140]:
notsix([1234, 6783, 6, 4321, 9876])

[1234, 4321, 9876]

Question #19: Challenging. Explain what this code does:

In [143]:
old_list = [1234, 6783, 6, 4321, 9876] 
new_list = [x for x in old_list if str(x)[0] != "6"]

Answer:

The first line assigns the list [1234, 6783, 6, 4321, 9876] to variable old_list.

The second line creates a new list using integers only that do not start with 6, which can be checked below. 

In [144]:
new_list

[1234, 4321, 9876]

Question #20: Consider the Python object z = {1: 'one', 2: 'two', 3: 'three}

a. What kind of object is z? What is its length?

In [141]:
z = {1: 'one', 2: 'two', 3: 'three'}
type(z)

dict

In [120]:
len(z)

3

Answer:

z is a dictionary and its length is 3.

b. Which components are keys? Which are values?

In [130]:
z.keys()

dict_keys([1, 2, 3])

In [131]:
z.values()

dict_values(['one', 'two', 'three'])

Answer:

Components 1, 2, 3 are keys and componenets one, two, three are values.

c. How would I get the value associated with the key 2?

In [136]:
list(z.keys())[1]

2

d. Use Spyder’s help facilities to figure out what z.keys() does. Ditto z.values(). Try them to verify.

In [137]:
z.keys?

Answer:

z.keys is the command that displays the keys from dictionary d.

In [147]:
z.keys()

dict_keys([1, 2, 3])

In [144]:
z.values?

Answer:

z.values is the command that displays the values from dictionary d.

In [149]:
z.values()

dict_values(['one', 'two', 'three'])

e. What does list(z.keys()) do?

In [138]:
list(z.keys())

[1, 2, 3]

Answer:

list(z.keys()) converts all the keys in dictionary z into a list. 

f. What does list(z.values()) do?

In [139]:
list(z.values())

['one', 'two', 'three']

Answer:

list(z.values()) converts all the values in dictionary z into a list. 

g. What does list(z) do?

In [142]:
list(z)

[1, 2, 3]

Answer:

list(z) converts the keys in the dictionary z into a list.